### PR TITLE
Make explicit cross-version support for Pydantic

### PR DESCRIPTION
**Pull request by cmungall**
curies is a distal transitive dependency of many packages, it needs to be neutral w.r.t pydantic version. It looks like it already is, and the pinning to <2 is unneccessary

For more context see https://github.com/biopragmatics/bioregistry/issues/920

### CODE REVIEW

**Comment by cthoyt** [comment]
I’d like to see explicit testing for both versions running. I tried this before and didn’t find it so easy unfortunately

**Comment by cmungall** [comment]
shall we get the sphinx fixed first then experiment with changes to gh actions to run with both versions of pydantic?

**Comment by matentzn** [comment]
High priority for me as well now! Thanks for getting the ball rolling!

**Comment by cthoyt** [comment]
I think it's the case that Pydantic rolled back some of its v1-v2 problems - one of the big issues was the config class that lives inside the actual base model subclass. This appears to be a "deprecation" now instead of being fully unavailable. This changes things wrt the previous try, making this easier. I have now solved all of the documentation and testing concerns, and can merge this + make a new release.

**Comment by cthoyt** [comment]
Release 0.6.0 reflects this update

**Pull request merged**
